### ISSUE TITLE
Blank page

### ISSUE THREAD

**Issue by mikweb2017** [nextcloud/photos#126]
### Steps to reproduce
select  photos  app

### Expected behaviour
picture  view

### Actual behaviour
blank page

## Server configuration detail

**Operating system:** Linux 4.4.0-166-generic #195-Ubuntu SMP Tue Oct 1 09:35:25 UTC 2019 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.28

**PHP version:** 

7.3.13
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, apcu, bcmath, curl, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, json, ldap, exif, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, snmp, soap, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache, xdebug

**Nextcloud version:** 18.0.0 RC2 - 18.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - analytics: 2.0.0
 - bookmarks: 2.3.4
 - calendar: 2.0.0
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.1.6
 - dashboardcharts: 0.1.3
 - dav: 1.14.0
 - drawio: 0.9.4
 - encryption: 2.6.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_accesscontrol: 1.8.1
 - files_automatedtagging: 1.8.0
 - files_external: 1.9.0
 - files_frommail: 0.3.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - forms: 1.1.0
 - groupfolders: 6.0.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.0.0
 - maps: 0.1.2
 - metadata: 0.10.0
 - music: 0.12.1
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - photos: 1.0.0
 - previewgenerator: 2.2.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - radio: 0.6.5
 - rainloop: 6.0.4
 - richdocuments: 3.5.1
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - sociallogin: 2.4.1
 - socialsharing_email: 1.0.6
 - socialsharing_facebook: 1.0.5
 - socialsharing_twitter: 1.0.5
 - spreed: 8.0.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.11.3
 - text: 1.2.3
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_totp: 4.1.2
 - unsplash: 1.1.4
 - updatenotification: 1.8.0
 - video_converter: 0.1.2
 - viewer: 1.2.0
 - workflow_pdf_converter: 1.3.1
 - workflow_script: 1.3.1
 - workflowengine: 2.0.0
Disabled:
 - audioplayer
 - dashboard
 - deck
 - event_update_notification
 - files_fulltextsearch_tesseract
 - files_mindmap
 - impersonate
 - ocr
 - password_policy
 - recommendations
 - social
 - talk_simple_poll
 - uploaddetails
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.mikweb.eu"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.0.9",
    "overwrite.cli.url": "http:\/\/cloud.mikweb.eu",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "mail_smtpdebug": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "filelocking.enabled": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "updater.release.channel": "beta",
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "twofactor_enforced": "false",
    "twofactor_enforced_groups": [],
    "twofactor_enforced_excluded_groups": [],
    "app_install_overwrite": [
        "apporder",
        "radio",
        "end_to_end_encryption",
        "photosphereviewer",
        "sensorlogger",
        "activitylog",
        "files_reader",
        "metadata",
        "unsplash",
        "socialsharing_facebook",
        "video_converter",
        "socialsharing_email",
        "socialsharing_twitter",
        "dashboard",
        "maps",
        "forms",
        "drawio",
        "rainloop",
        "files_frommail",
        "event_update_notification"
    ],
    "mail_sendmailmode": "pipe",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Thu Jan 16 21:48:36.600551 2020] [access_compat:error] [pid 12907] [client 91.65.147.230:49237] AH01797: client denied by server configuration: /var/www/vhosts/cloud.mikweb.eu/httpdocs/config
[Fri Jan 17 06:26:04.501652 2020] [access_compat:error] [pid 6356] [client 91.65.147.230:49212] AH01797: client denied by server configuration: /var/www/vhosts/cloud.mikweb.eu/httpdocs/config
[Fri Jan 17 06:26:04.779911 2020] [access_compat:error] [pid 25197] [client 91.65.147.230:49214] AH01797: client denied by server configuration: /var/www/vhosts/cloud.mikweb.eu/httpdocs/config
[Fri Jan 17 19:05:30.449191 2020] [core:crit] [pid 28144] (13)Permission denied: [client 91.65.147.230:57928] AH00529: /var/www/vhosts/cloud.mikweb.eu/httpdocs/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/vhosts/cloud.mikweb.eu/httpdocs/data/' is executable
[Fri Jan 17 19:11:56.076773 2020] [proxy_fcgi:error] [pid 29547] (104)Connection reset by peer: [client 91.65.147.230:56994] AH01075: Error dispatching request to : (passing brigade to output filters)
[Fri Jan 17 19:11:56.206715 2020] [proxy_fcgi:error] [pid 30140] (32)Broken pipe: [client 91.65.147.230:56998] AH01075: Error dispatching request to : (passing brigade to output filters)
[Fri Jan 17 19:11:57.631072 2020] [proxy_fcgi:error] [pid 29695] (32)Broken pipe: [client 91.65.147.230:57000] AH01075: Error dispatching request to : (passing brigade to output filters)
[Fri Jan 17 19:11:59.074162 2020] [proxy_fcgi:error] [pid 30201] (32)Broken pipe: [client 91.65.147.230:57004] AH01075: Error dispatching request to : (passing brigade to output filters)
[Fri Jan 17 19:12:00.022866 2020] [proxy_fcgi:error] [pid 30125] (32)Broken pipe: [client 91.65.147.230:57002] AH01075: Error dispatching request to : (passing brigade to output filters)
[Fri Jan 17 19:12:00.775403 2020] [proxy_fcgi:error] [pid 29695] (104)Connection reset by peer: [client 91.65.147.230:57006] AH01075: Error dispatching request to : (passing brigade to output filters)
[Fri Jan 17 19:12:01.674819 2020] [proxy_fcgi:error] [pid 30119] (104)Connection reset by peer: [client 91.65.147.230:57010] AH01075: Error dispatching request to : (passing brigade to output filters)
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert \Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"Zd90fYXjgEOihUaPU7lp","level":1,"time":"2020-01-17T20:18:23+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"no app in context","method":"GET","url":"/index.php/settings/admin/issuetemplate","message":"Deprecated event type for \\OCP\\Files::preCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"Zd90fYXjgEOihUaPU7lp","level":1,"time":"2020-01-17T20:18:23+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"no app in context","method":"GET","url":"/index.php/settings/admin/issuetemplate","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"Zd90fYXjgEOihUaPU7lp","level":1,"time":"2020-01-17T20:18:23+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"no app in context","method":"GET","url":"/index.php/settings/admin/issuetemplate","message":"Deprecated event type for \\OCP\\Files::postCreate: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"Zd90fYXjgEOihUaPU7lp","level":1,"time":"2020-01-17T20:18:23+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"no app in context","method":"GET","url":"/index.php/settings/admin/issuetemplate","message":"Deprecated event type for \\OCP\\Files::preWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"Zd90fYXjgEOihUaPU7lp","level":1,"time":"2020-01-17T20:18:23+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"no app in context","method":"GET","url":"/index.php/settings/admin/issuetemplate","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"Zd90fYXjgEOihUaPU7lp","level":1,"time":"2020-01-17T20:18:23+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"no app in context","method":"GET","url":"/index.php/settings/admin/issuetemplate","message":"Deprecated event type for \\OCP\\Files::preWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"Zd90fYXjgEOihUaPU7lp","level":1,"time":"2020-01-17T20:18:23+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"no app in context","method":"GET","url":"/index.php/settings/admin/issuetemplate","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"Zd90fYXjgEOihUaPU7lp","level":1,"time":"2020-01-17T20:18:23+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"no app in context","method":"GET","url":"/index.php/settings/admin/issuetemplate","message":"Deprecated event type for \\OCP\\Files::preWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"Zd90fYXjgEOihUaPU7lp","level":1,"time":"2020-01-17T20:18:23+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"no app in context","method":"GET","url":"/index.php/settings/admin/issuetemplate","message":"Deprecated event type for \\OCP\\Files::postWrite: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"Zd90fYXjgEOihUaPU7lp","level":0,"time":"2020-01-17T20:18:23+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"core","method":"GET","url":"/index.php/settings/admin/issuetemplate","message":"SCSSCacher: /apps/issuetemplate/css/style.scss compiled and successfully cached","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"35x1IS5unjLK8quX8j1V","level":3,"time":"2020-01-17T20:20:14+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"PHP","method":"POST","url":"/index.php/apps/issuetemplate/render","message":"Undefined index: client-detail at /var/www/vhosts/cloud.mikweb.eu/httpdocs/apps/issuetemplate/lib/Detail.php#59","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"35x1IS5unjLK8quX8j1V","level":3,"time":"2020-01-17T20:20:14+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"PHP","method":"POST","url":"/index.php/apps/issuetemplate/render","message":"Undefined index: client-detail at /var/www/vhosts/cloud.mikweb.eu/httpdocs/apps/issuetemplate/lib/Detail.php#59","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"35x1IS5unjLK8quX8j1V","level":3,"time":"2020-01-17T20:20:14+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"PHP","method":"POST","url":"/index.php/apps/issuetemplate/render","message":"Undefined index: log-detail at /var/www/vhosts/cloud.mikweb.eu/httpdocs/apps/issuetemplate/lib/Detail.php#59","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"35x1IS5unjLK8quX8j1V","level":3,"time":"2020-01-17T20:20:14+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"PHP","method":"POST","url":"/index.php/apps/issuetemplate/render","message":"Undefined index: log-detail at /var/www/vhosts/cloud.mikweb.eu/httpdocs/apps/issuetemplate/lib/Detail.php#59","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"35x1IS5unjLK8quX8j1V","level":3,"time":"2020-01-17T20:20:14+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"PHP","method":"POST","url":"/index.php/apps/issuetemplate/render","message":"Undefined index: log-detail at /var/www/vhosts/cloud.mikweb.eu/httpdocs/apps/issuetemplate/lib/Detail.php#59","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"2NXhm4k9zjkDm2VoMS4U","level":3,"time":"2020-01-17T20:20:22+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"PHP","method":"POST","url":"/index.php/apps/issuetemplate/render","message":"Undefined index: log-detail at /var/www/vhosts/cloud.mikweb.eu/httpdocs/apps/issuetemplate/lib/Detail.php#59","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"2NXhm4k9zjkDm2VoMS4U","level":3,"time":"2020-01-17T20:20:22+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"PHP","method":"POST","url":"/index.php/apps/issuetemplate/render","message":"Undefined index: log-detail at /var/www/vhosts/cloud.mikweb.eu/httpdocs/apps/issuetemplate/lib/Detail.php#59","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"}
{"reqId":"2NXhm4k9zjkDm2VoMS4U","level":3,"time":"2020-01-17T20:20:22+00:00","remoteAddr":"91.65.147.230","user":"mikweb2014","app":"PHP","method":"POST","url":"/index.php/apps/issuetemplate/render","message":"Undefined index: log-detail at /var/www/vhosts/cloud.mikweb.eu/httpdocs/apps/issuetemplate/lib/Detail.php#59","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.108 Safari/537.36","version":"18.0.0.9"} Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
ProxyBus.js:65 Proxying an event bus of version 1.0.0 with 0.2.1
t @ ProxyBus.js:65
globals.js:66 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:66
ProxyBus.js:65 Proxying an event bus of version 1.0.0 with 0.2.1
e @ ProxyBus.js:65
globals.js:66 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:66
activity-sidebar.js?v=dcbe57a0-30:486 Uncaught TypeError: Cannot read property 'DetailTabView' of undefined
    at activity-sidebar.js?v=dcbe57a0-30:486
    at activity-sidebar.js?v=dcbe57a0-30:686
globals.js:66 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:66
commentmodel.js:13 Uncaught TypeError: Cannot read property 'Client' of undefined
    at commentmodel.js:13
    at Object.<anonymous> (commentmodel.js:11)
    at n (bootstrap:19)
    at Module.<anonymous> (comments.js:1)
    at n (bootstrap:19)
    at bootstrap:83
    at comments.js?v=dcbe57a0-30:1
ProxyBus.js:65 Proxying an event bus of version 1.0.0 with 0.2.1
t @ ProxyBus.js:65
ProxyBus.js:65 Proxying an event bus of version 1.0.0 with 0.2.1
t @ ProxyBus.js:65
ProxyBus.js:65 Proxying an event bus of version 1.0.0 with 0.2.1
t @ ProxyBus.js:65
ProxyBus.js:65 Proxying an event bus of version 1.0.0 with 0.2.1
t @ ProxyBus.js:65
ShareSearch.js:33 OCA.Sharing.ShareSearch initialized
ExternalLinkActions.js:33 OCA.Sharing.ExternalLinkActions initialized
globals.js:66 Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20
ne @ globals.js:66
versionstabview.js:18 Uncaught TypeError: Cannot read property 'DetailTabView' of undefined
    at Module.<anonymous> (versionstabview.js:18)
    at n (bootstrap:19)
    at bootstrap:83
    at files_versions.js?v=dcbe57a0-30:1
ProxyBus.js:65 Proxying an event bus of version 1.0.0 with 0.2.1
t @ ProxyBus.js:65
Viewer.js:40 OCA.Viewer initialized
Viewer.vue:234 No OCA.Files found, viewer is now in standalone mode
semver sync:4 Uncaught Error: Cannot find module './functions/valid'
    at n (semver sync:2)
    at index.js:3
    at Object.get [as valid] (index.js:10)
    at new t (ProxyBus.js:70)
    at Object.<anonymous> (index.js:20)
    at i (bootstrap:63)
    at Object.<anonymous> (requesttoken.js:9)
    at i (bootstrap:63)
    at Object.<anonymous> (index.js:25)
    at i (bootstrap:63)
Sidebar.js:37 OCA.Files.Sidebar initialized

</details>

**Comment by mikweb2017** [comment]
i dont now waht happen ...work now again

**Comment by skjnldsv** [comment]
Most likely a cache issue :)

**Comment by tillwf** [comment]
I have exactly the same problem since I switched to NC 18 RC2:

![image](https://user-images.githubusercontent.com/7115035/72669681-f749c380-3a2c-11ea-86af-1487f9ad5f69.png)

I tried on different browsers in private mode to have a fresh cache, but it didn't help.

Do I have to do something on the server side ?

**Comment by PaulLereverend** [comment]
Same here

**Comment by githubos1** [comment]
same issue after upgrade to 18.0.0 RC2

Blank page !!

**Comment by martin-nohava** [comment]
Exactly the same behavior as mentioned above. Updated thru Nextcloud Updater from 17 to 18.0.0 RC2 and after opening photos app I see just blank page.

**Comment by ThoDor-NC** [comment]
Me too after upgrading from 17 to 18.
Empty Cache did nothing. Even disable / enable Plugin didn't help.....

**Comment by skjnldsv** [comment]
Yes, rc2 is broken, use latest stable18!

**Comment by tillwf** [comment]
@skjnldsv For those who are using nextcloud's gui to upgrade the version there is no update available. Do you know when will the new release be available ? In the meantime, is there a way to patch nextcloud to get the app working ? Thanks

**Comment by skjnldsv** [comment]
Unfortunately no.
You can manually update your server if you want
